name: Deploy to Azure

on:
  push:
    branches:
      - main  # Workflow akan berjalan jika ada perubahan pada branch `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Deploy to Azure
      run: |
        echo "Deploying aplikasi ke Azure"
        # Tambahkan perintah deployment Azure di sini
